# ci pipeline
name: pre-commit

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch. Without this if check, checks are duplicated since
    # internal PRs match both the push and pull_request events.
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          # python -m pip install -e '.[d]'

      - name: poetry version
        run: poetry --version

      - name: Install pipeline dependencies
        run: python -m pip install black flake8 pytest isort

      - name: Install project dependencies
        run: python -m pip install sqlparse databricks-cli commitizen

      - name: black . --check
        run: black . --check --exclude 'test_notebooks'
        if: always()

      - name: flake8 .
        run: flake8 . --ignore=E501,E203,W503 --exclude 'test_notebooks'
        if: always()

      - name: isort . --check
        run: isort . --check
        if: always()

      - name: python -m pytest
        run: pytest
        if: always()
